sudo: false
language: go

services:
  - redis-server

go:
  - 1.7
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get gopkg.in/redis.v5
  - go get gopkg.in/go-redis/rate.v5
  - go get gopkg.in/vmihailenco/msgpack.v2
  - go get github.com/iron-io/iron_go3/mq
  - go get github.com/aws/aws-sdk-go/service/sqs
  - mkdir -p $HOME/gopath/src/gopkg.in
  - mv `pwd` $HOME/gopath/src/gopkg.in/msgqueue.v1
