sudo: false
language: go

services:
  - redis-server

go:
  - 1.7
  - 1.8
  - tip

matrix:
  allow_failures:
    - go: tip

install:
  - go get github.com/onsi/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/go-redis/redis
  - go get github.com/go-redis/rate
  - go get gopkg.in/vmihailenco/msgpack.v2
  - go get github.com/iron-io/iron_go3/mq
  - go get github.com/aws/aws-sdk-go/service/sqs
